name: AWS identity check

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  identity:
    runs-on: ubuntu-latest
    environment: <GITHUB_ENVIRONMENT>
    steps:
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.AWS_CONFIG_ROLE_ARN }}
          aws-region: ${{ vars.AWS_REGION }}
      - run: aws sts get-caller-identity

